### ISSUE TITLE
Add Screenshots of the App

### ISSUE THREAD

**Issue by nikhilbansal97** [nikhilbansal97/Memory-Game#2]
Add some screenshots of the app in the `README.md` file. The screenshots should not be too big or small.

**Comment by ananya1304** [comment]
I am taking this up.

**Comment by nikhilbansal97** [comment]
Sure @ananya1304 Go ahead!

**Comment by nikhilbansal97** [comment]
@ananya1304 Your PR has been merged! 🎉
