### ISSUE TITLE
Add custom dialog box which appears when the user wins

### ISSUE THREAD

**Issue by nikhilbansal97** [nikhilbansal97/Memory-Game#4]
After the user has won the game, a custom dialog box should appear Congratulating the suer and it will reset the game.

The dialog box should be easy to use so that it can further be used for other purposes such as "Maximum tries reached!" case. You can use any open source library for this.

**Comment by rabross** [comment]
Related to #5 so I could pick up both at once

**Comment by rabross** [comment]
PR is up #6

**Comment by rabross** [comment]
@nikhilbansal97 You can close this one.
