### ISSUE TITLE
Add a limit to number of tries.

### ISSUE THREAD

**Issue by nikhilbansal97** [nikhilbansal97/Memory-Game#5]
Currently the user can try unlimited number of times to guess the icons behind the tiles. Add a logic to limit the number of tries.

**Comment by rabross** [comment]
What would happen when the player reaches the limit? Game over?

**Comment by nikhilbansal97** [comment]
@rabross A dialog box will appear showing "Game Over" and the game will reset

**Comment by rabross** [comment]
I can do this one then

**Comment by rabross** [comment]
PR is up #6

**Comment by nikhilbansal97** [comment]
@rabross I have reviewed the PR. Can you have a look at it?
